GET http://localhost:5000/api/leads/123
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtaWxhZEB4LmNvbSIsImV4cCI6MTczNDY4ODY4MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTc5IiwiYXVkIjoibG9naW4uYXZlZHNvLmNvbSJ9._WrcVc7Rw-uyhHIUJDtxvRiX85HJDDzOUNWvN45W_0w
###

GET http://localhost:5000/api/leads
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtaWxhZEB4LmNvbSIsImV4cCI6MTczNDY4ODY4MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTc5IiwiYXVkIjoibG9naW4uYXZlZHNvLmNvbSJ9._WrcVc7Rw-uyhHIUJDtxvRiX85HJDDzOUNWvN45W_0w
###